### ISSUE TITLE
Refactor TSML import ajax

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#1469]
looks like $remaining is never set if there are no $meetings in the import buffer. fixing this should solve a 500 error that a site is getting

```
[22-Jul-2024 14:28:14 UTC] PHP Warning:  Undefined variable $remaining in /wp-content/plugins/12-step-meeting-list/includes/ajax.php on line 609
[22-Jul-2024 14:28:14 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /wp-content/plugins/12-step-meeting-list/includes/ajax.php:609
Stack trace:
#0 /wp-includes/class-wp-hook.php(324): {closure}()
#1 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /wp-admin/admin-ajax.php(192): do_action()
#4 {main}
  thrown in /wp-content/plugins/12-step-meeting-list/includes/ajax.php on line 609
[22-Jul-2024 14:29:52 UTC] PHP Warning:  Undefined variable $remaining in /wp-content/plugins/12-step-meeting-list/includes/ajax.php on line 609
[22-Jul-2024 14:29:52 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /wp-content/plugins/12-step-meeting-list/includes/ajax.php:609
Stack trace:
#0 /wp-includes/class-wp-hook.php(324): {closure}()
#1 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /wp-admin/admin-ajax.php(192): do_action()
#4 {main}
  thrown in /wp-content/plugins/12-step-meeting-list/includes/ajax.php on line 609
[22-Jul-2024 14:33:08 UTC] PHP Warning:  Undefined variable $remaining in /wp-content/plugins/12-step-meeting-list/includes/ajax.php on line 609
[22-Jul-2024 14:33:08 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /wp-content/plugins/12-step-meeting-list/includes/ajax.php:609
Stack trace:
#0 /wp-includes/class-wp-hook.php(324): {closure}()
#1 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /wp-admin/admin-ajax.php(192): do_action()
#4 {main}
  thrown in /wp-content/plugins/12-step-meeting-list/includes/ajax.php on line 609
[22-Jul-2024 14:50:45 UTC] PHP Warning:  Undefined variable $remaining in /wp-content/plugins/12-step-meeting-list/includes/ajax.php on line 609
[22-Jul-2024 14:50:45 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /wp-content/plugins/12-step-meeting-list/includes/ajax.php:609
Stack trace:
#0 /wp-includes/class-wp-hook.php(324): {closure}()
#1 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /wp-admin/admin-ajax.php(192): do_action()
#4 {main}
  thrown in /wp-content/plugins/12-step-meeting-list/includes/ajax.php on line 609
```

while we're at it, would be good to add the value of WP_DEBUG to the tsml_info ajax

**Comment by joshreisner** [comment]
seeing a few more issues
```
07/23/24 01:16:47 - init with cfg result : 
[23-Jul-2024 12:34:40 UTC] PHP Warning:  Undefined array key "status" in /wp-content/plugins/12-step-meeting-list/includes/ajax.php on line 428
[23-Jul-2024 12:55:41 UTC] PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /wp-content/plugins/12-step-meeting-list/includes/functions.php:245
Stack trace:
#0 /wp-content/plugins/12-step-meeting-list/includes/functions.php(245): array_merge()
#1 /wp-content/themes/Divi-child/functions.php(22): tsml_custom_addresses()
#2 /wp-settings.php(663): include('/home/u74505162...')
#3 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1374): require('/home/u74505162...')
#4 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1293): WP_CLI\Runner->load_wordpress()
#5 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#6 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process()
#7 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#8 phar:///usr/local/bin/wp-cli-2.10.0.phar/php/boot-phar.php(20): include('phar:///usr/loc...')
#9 /usr/local/bin/wp-cli-2.10.0.phar(4): include('phar:///usr/loc...')
#10 {main}
  thrown in /wp-content/plugins/12-step-meeting-list/includes/functions.php on line 245
[23-Jul-2024 12:55:42 UTC] PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /wp-content/plugins/12-step-meeting-list/includes/functions.php:245
Stack trace:
#0 /wp-content/plugins/12-step-meeting-list/includes/functions.php(245): array_merge()
#1 /wp-content/themes/Divi-child/functions.php(22): tsml_custom_addresses()
#2 /wp-settings.php(663): include('/home/u74505162...')
#3 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1374): require('/home/u74505162...')
#4 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1293): WP_CLI\Runner->load_wordpress()
#5 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#6 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process()
#7 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#8 phar:///usr/local/bin/wp-cli-2.10.0.phar/php/boot-phar.php(20): include('phar:///usr/loc...')
#9 /usr/local/bin/wp-cli-2.10.0.phar(4): include('phar:///usr/loc...')
#10 {main}
  thrown in /wp-content/plugins/12-step-meeting-list/includes/functions.php on line 245
[23-Jul-2024 12:55:44 UTC] PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /wp-content/plugins/12-step-meeting-list/includes/functions.php:245
Stack trace:
#0 /wp-content/plugins/12-step-meeting-list/includes/functions.php(245): array_merge()
#1 /wp-content/themes/Divi-child/functions.php(22): tsml_custom_addresses()
#2 /wp-settings.php(663): include('/home/u74505162...')
#3 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1374): require('/home/u74505162...')
#4 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1293): WP_CLI\Runner->load_wordpress()
#5 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#6 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process()
#7 phar:///usr/local/bin/wp-cli-2.10.0.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#8 phar:///usr/local/bin/wp-cli-2.10.0.phar/php/boot-phar.php(20): include('phar:///usr/loc...')
#9 /usr/local/bin/wp-cli-2.10.0.phar(4): include('phar:///usr/loc...')
#10 {main}
  thrown in /wp-content/plugins/12-step-meeting-list/includes/functions.php on line 245
```
