### ISSUE TITLE
error adding feeds with change detection enabled

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#789]
### What happened?

when adding a feed with change detection i see:

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function tsml_schedule_import_scan(), 0 passed in /home/forge/demo.code4recovery.org/wp-content/plugins/12-step-meeting-list/includes/admin_import.php on line 196 and exactly 2 expected in /home/forge/demo.code4recovery.org/wp-content/plugins/12-step-meeting-list/includes/functions.php:2162 Stack trace: #0 /home/forge/demo.code4recovery.org/wp-content/plugins/12-step-meeting-list/includes/admin_import.php(196): tsml_schedule_import_scan() #1 /home/forge/demo.code4recovery.org/wp-includes/class-wp-hook.php(307): tsml_import_page() #2 /home/forge/demo.code4recovery.org/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters() #3 /home/forge/demo.code4recovery.org/wp-includes/plugin.php(474): WP_Hook->do_action() #4 /home/forge/demo.code4recovery.org/wp-admin/admin.php(259): do_action() #5 /home/forge/demo.code4recovery.org/wp-admin/edit.php(10): require_once('...') #6 {main} thrown in /home/forge/demo.code4recovery.org/wp-content/plugins/12-step-meeting-list/includes/functions.php on line 2162
```

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

**Comment by kiyote33** [comment]
Fixed in 3.14.3
